# Generated by Django 2.1.7 on 2019-04-28 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0010_auto_20190426_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='notifications',
        ),
        migrations.AlterField(
            model_name='message',
            name='datetime',
            field=models.IntegerField(default=1556411002.0),
        ),
        migrations.AlterField(
            model_name='post',
            name='datetime',
            field=models.IntegerField(default=1556411002.0),
        ),
    ]
