# Generated by Django 2.1.7 on 2019-05-14 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0019_usernotification_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotification',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='usernotification',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserNotification',
        ),
    ]
