# Generated by Django 2.1.7 on 2019-05-14 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0020_auto_20190514_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='text',
            field=models.CharField(default='', max_length=80),
        ),
    ]
