# Generated by Django 2.1.7 on 2019-04-08 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='user', max_length=32)),
                ('message_text', models.CharField(max_length=1000)),
                ('room_name', models.CharField(default='lobby', max_length=200)),
                ('post_id', models.IntegerField(default=0)),
                ('datetime', models.IntegerField(default=1554685373.0)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='user', max_length=32)),
                ('topic', models.CharField(default='graytale', max_length=32)),
                ('url', models.URLField(max_length=250)),
                ('text', models.TextField(blank=True, max_length=10000)),
                ('title', models.CharField(default='', max_length=64)),
                ('datetime', models.IntegerField(default=1554685373.0)),
            ],
        ),
    ]
