# Generated by Django 2.1.7 on 2019-03-28 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='date',
        ),
    ]
