# Generated by Django 2.1.7 on 2019-03-28 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0002_remove_message_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='day',
            field=models.IntegerField(default=28),
        ),
        migrations.AddField(
            model_name='message',
            name='hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='minute',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='message',
            name='month',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='message',
            name='second',
            field=models.IntegerField(default=22),
        ),
        migrations.AddField(
            model_name='message',
            name='year',
            field=models.IntegerField(default=2019),
        ),
    ]
