# Generated by Django 2.1.7 on 2019-04-08 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatbox', '0003_auto_20190407_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriptions', models.ManyToManyField(to='chatbox.Topic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='datetime',
            field=models.IntegerField(default=1554685606.0),
        ),
        migrations.AlterField(
            model_name='post',
            name='datetime',
            field=models.IntegerField(default=1554685606.0),
        ),
    ]
