# Generated by Django 2.1.7 on 2019-03-28 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0003_auto_20190328_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='minute',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='second',
            field=models.IntegerField(default=33),
        ),
    ]
