# Generated by Django 2.1.7 on 2019-04-03 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0006_auto_20190328_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='user', max_length=32)),
                ('url', models.URLField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='day',
        ),
        migrations.RemoveField(
            model_name='message',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='message',
            name='minute',
        ),
        migrations.RemoveField(
            model_name='message',
            name='month',
        ),
        migrations.RemoveField(
            model_name='message',
            name='second',
        ),
        migrations.RemoveField(
            model_name='message',
            name='year',
        ),
        migrations.AddField(
            model_name='message',
            name='datetime',
            field=models.IntegerField(default=1554255588.0),
        ),
    ]
