# Generated by Django 2.1.7 on 2019-04-03 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0007_auto_20190402_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='message',
            name='datetime',
            field=models.IntegerField(default=1554259983.0),
        ),
    ]
