# Generated by Django 2.1.7 on 2019-04-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0009_auto_20190403_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='message',
            name='datetime',
            field=models.IntegerField(default=1554310446.0),
        ),
    ]
