# Generated by Django 2.1.7 on 2019-04-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0010_auto_20190403_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='datetime',
            field=models.IntegerField(default=1554310453.0),
        ),
    ]
