# Generated by Django 2.1.7 on 2019-04-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0012_auto_20190403_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='post_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='message',
            name='datetime',
            field=models.IntegerField(default=1554317237.0),
        ),
        migrations.AlterField(
            model_name='post',
            name='datetime',
            field=models.IntegerField(default=1554317237.0),
        ),
    ]
