# Generated by Django 2.1.7 on 2019-04-29 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0013_auto_20190429_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='post_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbox.Post'),
        ),
    ]
