# Generated by Django 2.1.7 on 2019-05-01 23:58

import chatbox.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0015_remove_post_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='', validators=[chatbox.models.validate_size]),
        ),
    ]
