# Generated by Django 2.1.7 on 2019-05-05 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0016_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='metaimage',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
