# Generated by Django 2.1.7 on 2019-05-14 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0018_usernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chatbox.Topic'),
        ),
    ]
