# Generated by Django 2.1.7 on 2019-05-14 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0023_auto_20190514_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='datetime',
            field=models.IntegerField(default=0),
        ),
    ]
