# Generated by Django 2.1.7 on 2019-05-15 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0024_notification_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='actor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='notification_actor', to=settings.AUTH_USER_MODEL),
        ),
    ]
