# Generated by Django 2.1.7 on 2019-05-20 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0026_auto_20190516_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='datetime',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notification',
            name='datetime',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='datetime',
            field=models.BigIntegerField(default=0),
        ),
    ]
